version: '3'

services:
  web:
    container_name: queueoverflow-web
    env_file:
      - .env
    build: .
    command: >
      bash -c "rails db:setup &&
      rails assets:precompile &&
      rails ts:index &&
      rails ts:start &&
      rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/QuestionsAndAnswers
    depends_on:
      - db

  db:
    container_name: queueoverflow-db
    image: postgres
    env_file:
      - .env
    volumes:
      - ./db/postgres:/var/lib/postgresql
      - ./db/log/postgres:/var/log/postgresql
      - ./db/ets/postgres:/etc/postgresql

  frontend:
    container_name: queueoverflow-frontend
    build: config/nginx
    depends_on:
      - web
    ports:
      - '80:80'
      - '443:443'
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
